### PR TITLE
PDEV-13 (Bug): Allow users to choose their indicator preferences and view indicators outside of their EMR

### PR DESCRIPTION
**Pull request by darshik**

### CODE REVIEW

**Comment by danielegli** [comment]
I really don't like the "Saved. Your preferences have been saved" that pops up over top of the toggle when you click it.  I think mostly because it covers up the toggle I just clicked and now I can't see what the toggle did.

**Comment by danielegli** [comment]
Also need a second change done so that when an organization's EMR type is changed, the label on the toggle gets updated too.

**Comment by darshik** [comment]
addressed the changes requested in the code review

**Comment by danielegli** [comment]
Seems to work now.  I tested created both an OSCAR and an Accuro clinic and they defaulted to the right options.

**Pull request merged**
